# Generated by Django 4.2.6 on 2023-12-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comments_user_alter_comments_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='total_kpi',
            field=models.IntegerField(default=0),
        ),
    ]
