# Generated by Django 4.2.6 on 2023-12-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_data_total_kpi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='month_kpi',
        ),
    ]
