# Generated by Django 4.2.6 on 2023-12-21 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_data_month_kpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsibilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.CharField(max_length=1000)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='main.data')),
            ],
        ),
    ]
